#+TITLE: Econ202A Homework #2
#+AUTHOR: Chris Ackerman, Eketerina Gurkova, Ali Haider Ismail, and Ben Pirie 
#+LATEX_HEADER: \usepackage{amsthm}
#+LATEX_HEADER: \usepackage{url}
#+LATEX_HEADER: \usepackage[margin=1.25in]{geometry}
#+LATEX_HEADER: \usepackage{hyperref} 
#+LATEX_HEADER: \usepackage[dvipsnames]{xcolor}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \newtheorem*{definition}{Definition}
#+LATEX_HEADER: \newtheorem*{example}{Example}
#+LATEX_HEADER: \newtheorem*{theorem}{Theorem}
#+LATEX_HEADER: \newtheorem*{corollary}{Corollary}
#+LATEX_HEADER: \newtheorem*{exercise}{Exercise}
#+LATEX_HEADER: \newtheorem*{problem}{Problem}
#+LATEX_HEADER: \newtheorem{question}{Question}
#+LATEX_HEADER: \newcommand{\gr}{\textcolor{ForestGreen}}
#+LATEX_HEADER: \newcommand{\rd}{\textcolor{red}}
#+LATEX_HEADER: \newcommand{\R}{\mathbb{R}}
#+LATEX_HEADER: \newcommand{\p}{\mathbb{P}}
#+LATEX_HEADER: \newcommand{\frall}{\ \forall}
#+OPTIONS:  ':t toc:nil

\newpage

\begin{enumerate}
\item In this economy, assume that $r = \delta$. Prove Hall’s Corollary 1 and 2, and 4. In addition, how would you go about estimating the implied regression in Corrolary 4?

\newpage
\item Explain the economic intuition for why the stochastic process for income is irrelevant in terms of being able to forecast future consumption. 

\newpage
\item Explain the economic intuition why if $r < \delta$, then consumption evolves as a random walk with positive drift, in which there is a constant term in theregression that is negative. 

\newpage
\item  Obtain quarterly real consumption (in chained dollars) from the U.S.
national income and product accounts from 1950 through 2019. Fit the following
regression:
\[
\ln(c_t) = \mu + \lambda \ln(c_{t-1}) + u_t
\]

\newpage
\item  Do you think that this is a reasonable statistical model of the log of
consumption? (Your answer to this question may include a discussion regarding
the value of the autoregressive coefficient, the R-square, and whether there is
autocorrelation in the $u_t$ residuals.)

\newpage
Next, consider the following economy.
\begin{align*}
\max & E_0 \sum^\infty_{t = 0}\beta^t \ln (c_t)\\
\intertext{subject to}
z_t A_t^{1 - \theta} k_t^\theta + (1 - \delta)k_t &= c_t + k_{t + 1}\\
A_t &= (1 + \gamma)^t, \quad t = 0, 1, \ldots \\
\ln(z_t) &= \rho \ln (z_{t - 1}) + \varepsilon_t,\quad \varepsilon_t \sim \mathcal{N}(0, \sigma^2_\varepsilon)
\end{align*}

Assume that the time period is annual. Construct a detrended version of
this economy and show the first order conditions. Choose $\beta$ so that the return
to capital in the steady state of the detrended economy is five percent, choose
$\theta$ so that capital’s share of income is 30 percent, and choose a depreciation rate
such that the share of investment to GDP in the steady state is 20 percent.
Choose $\rho = 0.95$, $\sigma^2_\varepsilon
 = .002$ and $\gamma = 0.02$.

\begin{align}
\intertext{Rearranging terms, we have}
k_{t + 1} &= A-t^{1 - \theta} k_t^\theta + (1 - \delta) k_t - c_t\\
Y_t &= A_t^{1 - \theta} k_t^\theta\\
c_t &= (1 - \theta) A_t^{1 - \theta} k_t^\theta\\
\intertext{To detrend, divide by $A-t$. Let's define a few new variables,}
\hat{k}_t &= \frac{K_t}{A_t}\\
\hat{y}_t &= \frac{Y_t}{A_t}\\
\hat{c}_t &= \frac{C_t}{A_t}.\\
\intertext{Now, we can substitute these back into the original equations.}
\hat{k}_{t + 1} &= \hat{y}_t + (1 - \delta) \hat{k}_t - \hat{c}_t\\
\hat{y}_t &= \frac{k^\theta}{A^\theta}\\
\hat{c}_t &= (1 - \theta) \hat{y}_t.\\
\intertext{First order conditions give us}
\frac{1}{\hat{c}_t} &= \frac{\beta}{1 + \gamma} E_t \left\{\frac{1}{\hat{c}_{t + 1}}\left[\frac{\theta \hat{y}_{t + 1}}{\hat{k}_{t + 1}} + 1 - \delta \right]\right\}.\\
\intertext{In the steady state, we have}
\frac{\overline{k}}{\overline{y}} &= \frac{\theta \beta}{1 + \gamma - \beta (1 - \delta)}\\
\frac{\overline{c}}{\overline{y}} &= \frac{1 + \gamma - \beta(1 - \delta) - \theta \beta (1 + \gamma - 1 + \delta)}{1 + \gamma - \beta (1 - \delta)}.\tag{$\ast$}\label{consumption-share}\\
\intertext{Now let's solve for parameters. We're given $\gamma = 0.02$, and we have to figure out $\beta$, $\theta$ and $\delta$. Since we have Cobb Douglas production, $\theta = 0.3$. To solve for $\beta$, note that the 5\% return implies}
\beta &= \frac{1}{1.05}\\
&= 0.95238.\\
\intertext{To solve for $\delta$, we're going to use equation \ref{consumption-share}. We're told that investment in the steady state is 20\% of GDP, so that implies that consumption is 80\% of GDP,}
0.8 &= \frac{1.02 - 0.95238(1 - \delta) - 0.3 \cdot 0.95238 (1.02 - 1 + \delta)}{1.02 - 0.95238 (1 - \delta)}\\
\implies \delta &= .082.
\end{align}

\newpage
\item 
 Log-linearize this model around its deterministic steady state. (For sim-
plicity, assume that $z$ in the steady state is 1).

\newpage
\item Use the formula of Blanchard and Kahn to show that there is a unique
stationary solution to the linearized system.

\newpage
\item Using a random number generator (Matlab has a built-in function for
this), draw 1100 values of $\varepsilon$ to construct the $z$ process. Using these values of $z$,
and assuming that $k_0$ is equal to its steady state value, use the linearized system
to construct 1100 values values of output, consumption, and investment.

\newpage
\item Discard the first 100 observations, and then fit an AR(1) process to the
log of consumption, measured as the log-deviation of consumption from the
steady state value. Report the value of the AR(1) coefficient in the regression,
and evaluate whether there is autocorrelation in the residuals.

\newpage
\item Compare the regression coefficient in (9) and your assessment of the
autocorrelation in the residuals, to your answers in (4) and (5). Does the RBC
model provide a good approximation to consumption dynamics? What does it
tell us about using consumption data to try to discriminate between the Hall
\end{enumerate}
